name: Build

on:
  pull_request_review:
    types: [submitted]
    
jobs:
  build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: npm install, build, test
      run: |
        npm i
        npm run build
        npm run test

